<?php
$z[0]=Array("arcurl","",17,32);
$z[1]=Array("title","",41,55);
$z[2]=Array("autoindex","@me=\$GLOBALS['autoindex'];",104,178);
$z[2][4]['runphp']="yes";
$z[3]=Array("autoindex","@me=\$GLOBALS['autoindex'];",180,254);
$z[3][4]['runphp']="yes";
$z[4]=Array("autoindex","@me=\$GLOBALS['autoindex'];",280,354);
$z[4][4]['runphp']="yes";
$z[5]=Array("arcurl","",365,380);
$z[6]=Array("title","",382,396);
$z[7]=Array("title","",444,458);
$z[8]=Array("pubdate","",489,536);
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("click","",555,569);

?>