<li>

            <a href="[field:arcurl/]" title="[field:title/]" class="imga fl"><img src="[field:photo/]"/></a>
            <div class="info fl">
                <a href="[field:arcurl/]" title="[field:name/]" class="name fyahei">[field:name/]</a>
                <p><span class="fb">担任职务：</span>[field:job/]</p>
                <p><span class="fb">工作经验：</span>[field:experience/]</p>                
				<p><span class="fb">收费标准：</span>[field:collectfees/]</p>               
                <a href="{field:global.cfg_cmsurl