









<field:process itemname="施工进度" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:process>

<field:house itemname="房屋户型" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:house>

<field:style itemname="设计风格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:style>

<field:body itemname="详细信息" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:body>
