<?php
$z[0]=Array("global","",8,75);
$z[0][4]['name']="autoindex";
$z[0][4]['function']="@me%4==0?@me='end':@me=''";
$z[1]=Array("arcurl","",91,106);
$z[2]=Array("title","",115,129);
$z[3]=Array("litpic","",170,185);
$z[4]=Array("title","",192,206);
$z[5]=Array("title","",274,288);
$z[6]=Array("title","",321,335);
$z[7]=Array("title","",461,475);
$z[8]=Array("pubdate","",572,619);
$z[8][4]['function']="MyDate('Y-m-d',@me)";

?>