<ul class="moreTeam2 fl">
		<li class="">
            <a href="/plus/view.php?aid=[field:aid/]" target="_blank" class="imga"><img src="[field:photo/]" alt="[field:name/]"></a>
            <div class="info">
                <a href="" title="{dede:field.dsnname/}" target="_blank" class="fyahei">[field:name/]</a>
                <p class="position">[设计师]</p>
                <p>工作经验：[field:experience/]</p>                <p>收费标准：[field:collectfees/]</p>            </div>
        </li>
    </ul>
		<div class="rArea2 fl">
                <a href="http://www.caibeid.com/a/appointment.html?id=[field:aid/]" title="立即预约这位设计师" target="_blank" class="trust"><span class="orange">0</span></a>
        </div>