<a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="imga fl"><img src="[field:litpic/]" alt="[field:title/]" /></a>
<a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="tt fyahei">[field:title/]</a>
<p>[field:infos/]</p>
<p class="fari"><i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</i><a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="more f99">Readmore</a></p>