<li  id=[field:global name=autoindex function="@me%4==0?@me='end':@me=''"/]>
			<a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="imga"><img src="[field:litpic/]" alt="[field:title/]" /></a>
			<div class="txt">
				<a href="/376.html" title="[field:title/]" target="_blank" class="tt dis">[field:title/]</a>
				<em class="fari fr">8</em>
					</div>
			<div class="date fari">
				<a href="/376.html" title="[field:title/]" target="_blank" class="dis f99">+ READ MORE</a>
			  <em class="fr">8</em>
				<em>DATE:[field:pubdate function="MyDate('Y-m-d',@me)"/]</em>
			</div>
			</li>