<li>
  <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="dis">
  <em class="col_[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]">[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]</em>
  <!--<li class="li[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]"><a href="[field:arcurl/]">[field:title/]</a></li>-->
  <div class="tt fyahei"><i>></i> [field:title/]</div>
  <p class="fari">DATE:[field:pubdate function="GetDateTimeMK(@me)"/]              READ:[field:click/]</p>
  </a>
</li>