<?php
$z[0]=Array("global","",8,75);
$z[0][4]['name']="autoindex";
$z[0][4]['function']="@me%4==0?@me='end':@me=''";
$z[1]=Array("arcurl","",90,105);
$z[2]=Array("title","",114,128);
$z[3]=Array("litpic","",169,184);
$z[4]=Array("title","",191,205);
$z[5]=Array("title","",268,282);
$z[6]=Array("title","",315,329);
$z[7]=Array("click","",359,373);
$z[8]=Array("title","",452,466);
$z[9]=Array("click","",537,551);
$z[10]=Array("pubdate","",571,618);
$z[10][4]['function']="MyDate('Y-m-d',@me)";

?>