
<field:施工进度 itemname="progress" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:施工进度>

<field:房屋户型 itemname="house" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:房屋户型>

<field:设计风格 itemname="style" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:设计风格>

<field:详细信息 itemname="body" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:详细信息>
