<?php
$z[0]=Array("arcurl","",9,24);
$z[1]=Array("title","",33,47);
$z[2]=Array("litpic","",91,106);
$z[3]=Array("title","",113,127);
$z[4]=Array("arcurl","",146,161);
$z[5]=Array("title","",170,184);
$z[6]=Array("title","",220,234);
$z[7]=Array("arcinfos","",243,260);
$z[8]=Array("pubdate","",285,332);
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("arcurl","",345,360);
$z[10]=Array("title","",369,383);

?>