<?php
$z[0]=Array("arcurl","",24,39);
$z[1]=Array("title","",48,62);
$z[2]=Array("litpic","",90,105);
$z[3]=Array("title","",112,126);
$z[4]=Array("arcurl","",239,254);
$z[5]=Array("title","",263,277);
$z[6]=Array("pubdate","",327,374);
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("click","",404,418);
$z[8]=Array("arcurl","",475,490);
$z[9]=Array("title","",499,513);
$z[10]=Array("title","",527,541);

?>