<li>
        	<a href="[field:arcurl/]" title="[field:title/]" class="imga fl"><img src="[field:litpic/]" alt="[field:title/]" /></a>
            <div class="rArea fl">
            	<div class="time fari fl">
                	<a href="[field:arcurl/]" title="[field:title/]" class="view">+ VIEW</a>
                    <i>[field:pubdate function="MyDate('Y-m-d',@me)"/]</i>
                    <em>[field:click/]</em>
            	</div>
                <h2><a href="[field:arcurl/]" title="[field:title/]" class="f14">[field:title/]</a></h2>
                <p> </p>
            </div>
        </li>