<?php
$z[0]=Array("arcurl","",13,28);
$z[1]=Array("title","",29,43);
$z[2]=Array("photo","",44,58);
$z[3]=Array("arcurl","",90,105);
$z[4]=Array("title","",114,128);
$z[5]=Array("photo","",146,160);
$z[6]=Array("arcurl","",226,241);
$z[7]=Array("name","",250,263);
$z[8]=Array("name","",285,298);
$z[9]=Array("job","",362,374);
$z[10]=Array("experience","",438,457);
$z[11]=Array("collectfees","",525,545);
$z[12]=Array("production","",824,843);

?>