
<field:contact itemname="业主姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:sex itemname="业主性别" autofield="1" type="radio" isnull="true" default="男，女"  maxlength="250" page="">
</field:sex>

<field:phone itemname="联系手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:楼盘地址 itemname="addr" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:楼盘地址>

<field:area itemname="使用面积" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:area>

<field:cost itemname="装修预算" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cost>

<field:unit itemname="户型" autofield="1" type="select" isnull="true" default="请选择,一居,两居,多居,办公空间,娱乐会所,大户型,复式,别墅,其它"  maxlength="250" page="">
</field:unit>
