<?php
$z[0]=Array("global","",7,74);
$z[0][4]['name']="autoindex";
$z[0][4]['function']="@me%3==0?@me='end':@me=''";
$z[1]=Array("arcurl","",98,113);
$z[2]=Array("title","",122,136);
$z[3]=Array("photo","",177,191);
$z[4]=Array("title","",198,212);
$z[5]=Array("arcurl","",278,293);
$z[6]=Array("name","",302,315);
$z[7]=Array("name","",348,361);
$z[8]=Array("job","",404,416);
$z[9]=Array("experience","",457,476);
$z[10]=Array("collectfees","",514,534);

?>