<?php
$z[0]=Array("arcurl","",24,39);
$z[1]=Array("title","",48,62);
$z[2]=Array("litpic","",90,105);
$z[3]=Array("title","",112,126);
$z[4]=Array("arcurl","",239,254);
$z[5]=Array("title","",263,277);
$z[6]=Array("pubdate","",327,372);
$z[6][4]['function']="MyDate('Y-m',@me)";
$z[7]=Array("pubdate","",402,445);
$z[7][4]['function']="MyDate('d',@me)";
$z[8]=Array("arcurl","",502,517);
$z[9]=Array("title","",526,540);
$z[10]=Array("title","",554,568);

?>