
<field:contact itemname="合同姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:sex itemname="性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>

<field:phone itemname="联系手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:addr itemname="楼盘地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:addr>

<field:manager itemname="原工程经理" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:manager>

<field:designer itemname="原设计师" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:designer>

<field:ztime itemname="装修日期" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ztime>

<field:wtime itemname="维修时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wtime>

<field:kind itemname="报修种类" autofield="1" type="radio" isnull="true" default="水电类,木制类,油漆类,地板类,其他"  maxlength="250" page="">
</field:kind>

<field:content itemname="维修说明" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
