<?php
$z[0]=Array("global","",11,78);
$z[0][4]['name']="autoindex";
$z[0][4]['function']="@me%2==0?@me='end':@me=''";
$z[1]=Array("arcurl","",94,109);
$z[2]=Array("title","",118,132);
$z[3]=Array("litpic","",173,188);
$z[4]=Array("title","",195,209);
$z[5]=Array("title","",277,291);
$z[6]=Array("title","",324,338);
$z[7]=Array("title","",464,478);
$z[8]=Array("pubdate","",575,622);
$z[8][4]['function']="MyDate('Y-m-d',@me)";

?>