<?php
$z[0]=Array("click","",31,45);
$z[1]=Array("autoindex","@me=\$GLOBALS['autoindex'];",164,238);
$z[1][4]['runphp']="yes";
$z[2]=Array("litpic","",349,364);
$z[3]=Array("click","",448,462);
$z[4]=Array("arcurl","",502,517);
$z[5]=Array("title","",526,540);
$z[6]=Array("autoindex","@me=\$GLOBALS['autoindex'];",590,664);
$z[6][4]['runphp']="yes";
$z[7]=Array("title","",668,682);
$z[8]=Array("arcurl","",709,724);
$z[9]=Array("title","",733,747);
$z[10]=Array("litpic","",788,803);
$z[11]=Array("title","",810,824);

?>