<!---->
	<em class="otaho fr">[field:click/]&nbsp;&nbsp;</em>
            <a href='~typelink~' title='~typename~' target="_blank" class="dis fl"><i class="otaho">[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]</i>~typename~</a>
            <a href='~typelink~' title='~typename~' target="_blank" class="imga"><img src="[field:litpic/]" alt='~typename~' /></a>
	<!---->
			     <li>
            <em class="otaho fr">[field:click/]&nbsp;&nbsp;</em>
            <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="dis fl"><i class="otaho">[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]</i>[field:title/]</a>
            <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="imga"><img src="[field:litpic/]" alt="[field:title/]" /></a>
        </li>