<li>
            <a href="[field:arcurl/]" title="[field:title/]" class="imga fl">[field:photo/]</a>
            <div class="info fl">
                <a href="[field:arcurl/]" title="[field:name/]" class="name fyahei">[field:name/]</a>
                <p><span class="fb">担任职务：</span>[field:job/]</p>
                <p><span class="fb">工作经验：</span>[field:experience/]</p>                
				<p><span class="fb">收费标准：</span>[field:collectfees/]</p>               
                <a href="/indent?designer=315" title="立即预约" target="_blank" class="team_btn order">立即预约</a>
            </div>
            <div class="work fl">
            	<p class="fb">代表作品</p>
                <pre class="pre">[field:production/]</pre>
            </div>
        </li>