<tr>
            <td>[field:title/]</td>
            <td class="orange">[field:process/]</td>
            <td>[field:house/]</td>
            <td>[field:style/]</td>
            <td>[field:area/]</td>
            <td>[field:cost/]</td>
            <td>[field:maneger/]</td>
            <td><a href="[field:arcurl/]" title="[field:title/]" class="orange">±¨Ãû</a></td>
            <td><a href="[field:arcurl/]" title="[field:title/]" class="view">ÏêÇé</a></td>
        </tr>