<ul class="moreTeam2 fl">
		<li class="">
            <a href="/plus/view.php?aid=[field:aid/]" target="_blank" class="imga"><img src="[field:photo/]" alt="[field:dsnname/]"></a>
            <div class="info">
                <a href="/plus/view.php?aid=[field:aid/]" title="[field:dsnname/]" target="_blank" class="fyahei">[field:dsnname/]</a>
                <p class="position">[[field:job/]]</p>
                <p>工作经验：[field:experience/]</p>
				<p>收费标准：[field:collectfees/]</p>
				<p>人气指数：[field:click/]</p>
				<p>设计理念：[field:designconcept/]</p>
			</div>
        </li>
    </ul>