<?php
$z[0]=Array("global","",35,102);
$z[0][4]['name']="autoindex";
$z[0][4]['function']="@me%4==0?@me='end':@me=''";
$z[1]=Array("arcurl","",118,133);
$z[2]=Array("title","",142,156);
$z[3]=Array("litpic","",197,212);
$z[4]=Array("title","",219,233);
$z[5]=Array("title","",301,315);
$z[6]=Array("title","",348,362);
$z[7]=Array("title","",488,502);
$z[8]=Array("pubdate","",599,646);
$z[8][4]['function']="MyDate('Y-m-d',@me)";

?>