<?php
$z[0]=Array("aid","",84,96);
$z[1]=Array("photo","",137,151);
$z[2]=Array("dsnname","",158,174);
$z[3]=Array("aid","",258,270);
$z[4]=Array("dsnname","",279,295);
$z[5]=Array("dsnname","",328,344);
$z[6]=Array("job","",387,399);
$z[7]=Array("experience","",440,459);
$z[8]=Array("collectfees","",487,507);
$z[9]=Array("click","",535,549);
$z[10]=Array("designconcept","",577,599);
$z[11]=Array("aid","",739,751);

?>