<?php
$z[0]=Array("body","	\n",0,156);
$z[0][4]['itemname']="文章内容";
$z[0][4]['autofield']="0";
$z[0][4]['notsend']="0";
$z[0][4]['type']="htmltext";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="1";
$z[0][4]['default']="";
$z[0][4]['maxlength']="";
$z[0][4]['page']="split";
$z[1]=Array("dsnname","\r\n",162,390);
$z[1][4]['itemname']="请填写完整设计师姓名，系统会根据设计师姓名匹配设计师资料";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="1";
$z[1][4]['default']="";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";

?>