
<field:contact itemname="业主姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:sex itemname="业主性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>


<field:phone itemname="联系手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>



<field:area itemname="使用面积" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:area>

<field:cost itemname="装修预算" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cost>

<field:unit itemname="户型" autofield="1" type="select" isnull="true" default="请选择,一居,两居,多居,办公空间,娱乐会所,大户型,复式,别墅,其它"  maxlength="250" page="">
</field:unit>

<field:dstyle itemname="装修风格" autofield="1" type="select" isnull="true" default="请选择,别墅复式,欧式风格,美式风格,中式风格,现代风格"  maxlength="250" page="">
</field:dstyle>

<field:designer itemname="预约设计师" autofield="1" type="select" isnull="true" default="请选则,方浩,丁鹏,叶华琴,袁旖梦,崔莺"  maxlength="250" page="">
</field:designer>

<field:content itemname="装修要求" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:dtime itemname="动工时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dtime>

<field:addr itemname="楼盘地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:addr>
