<li>
  <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="dis">
  <em class="col_2">[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]</em>
  <!--<li class="li[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]"><a href="[field:arcurl/]">[field:title/]</a></li>-->
  <div class="tt fyahei"><i>></i> [field:title/]</div>
  <p class="fari">DATE:[field:pubdate function="GetDateTimeMK(@me)"/]              READ:<script src="{dede:field name='phpurl'/}/count.php?view=yes&aid={dede:field name='id'/}&mid={dede:field name='mid'/}" type='text/javascript' language="javascript"></script></p>
  </a>
</li>