<?php
$z[0]=Array("arcurl","",17,32);
$z[1]=Array("title","",41,55);
$z[2]=Array("autoindex","@me=\$GLOBALS['autoindex'];",107,181);
$z[2][4]['runphp']="yes";
$z[3]=Array("autoindex","@me=\$GLOBALS['autoindex'];",207,281);
$z[3][4]['runphp']="yes";
$z[4]=Array("arcurl","",292,307);
$z[5]=Array("title","",309,323);
$z[6]=Array("title","",371,385);
$z[7]=Array("pubdate","",416,462);
$z[7][4]['function']="GetDateTimeMK(@me)";

?>