<li>
            <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="imga"><img src="[field:photo/]" alt="[field:title/]"></a>
            <div class="info">
                <a href="[field:arcurl/]" title="[field:name/]" target="_blank" class="fyahei">[field:name/]</a>
                <p class="position">[[field:job/]]</p>
                <p>工作经验：[field:experience/]</p>                <p>收费标准：[field:collectfees/]</p>            </div>
        </li>