<li>
  <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="dis">
  <em class="col_2">1</em>
  <div class="tt fyahei"><i>></i> [field:title/]</div>
  <p class="fari">DATE:[field:pubdate function="GetDateTimeMK(@me)"/]              READ:<script src="[field :name='phpurl'/]/count.php?view=yes&aid=[field: name='id'/]&mid=[field: name='mid'/]" type='text/javascript' language="javascript"></script></p>
  </a>
</li>