<li id=[field:global name=autoindex function="@me%3==0?@me='end':@me=''"/]>
            <a href="[field:arcurl/]" title="[field:title/]" class="imga"><img src="[field:litpic/]" alt="[field:title/]" /></a>
            <div class="txt">
                <a href="[field:arcurl/]" title="[field:title/]" class="tt dis">[field:title/]</a>
                <em class="fari fr">[field:click/]</em>
                            <em>设计：[field:dsnname/]</em>
                            </div>
            <div class="date fari">
                <a href="[field:arcurl/]" title="[field:title/]" class="dis f99">+ READ MORE</a>
                <em class="fr">[field:click/]</em>
                <em>DATE:[field:pubdate function="MyDate('Y-m-d',@me)"/]</em>
            </div>
        </li>