<?php
$z[0]=Array("arcurl","",29,44);
$z[1]=Array("title","",53,67);
$z[2]=Array("photo","",95,109);
$z[3]=Array("arcurl","",178,193);
$z[4]=Array("name","",202,215);
$z[5]=Array("name","",237,250);
$z[6]=Array("job","",314,326);
$z[7]=Array("experience","",390,409);
$z[8]=Array("collectfees","",477,497);
$z[9]=Array("global","",543,569);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("production","",801,820);

?>