
<field:contact itemname="合同姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:sex itemname="性别" autofield="1" type="radio" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>

<field:phone itemname="联系手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:addr itemname="楼盘地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:addr>

<field:manager itemname="原工程经理" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:manager>

<field:designer itemname="原设计师" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:designer>
