<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",310,339);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n	    ",529,676);
$z[4][4]['type']="son";
$z[4][4]['typeid']="19";
$z[4][4]['row']="7";
$z[5]=Array("type","[field:typelink/]",776,828);
$z[5][4]['typeid']="24";
$z[6]=Array("type","[field:typelink/]",962,1014);
$z[6][4]['typeid']="62";
$z[7]=Array("field","",1219,1248);
$z[7][4]['name']="typename";
$z[8]=Array("global","",1624,1653);
$z[8][4]['name']="cfg_biaodantel";
$z[9]=Array("include","",9375,9412);
$z[9][4]['filename']="footer.htm";

?>