<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",126,158);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",217,243);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",306,335);
$z[3][4]['name']="position";
$z[4]=Array("field","",335,354);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n      	  <li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n      	",540,777);
$z[5][4]['type']="son";
$z[5][4]['row']="7";
$z[5][4]['typeid']="11";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("global","",877,902);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1047,1072);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("field","",1280,1299);
$z[8][4]['name']="title";
$z[9]=Array("field","",1339,1357);
$z[9][4]['name']="body";
$z[10]=Array("include","",1392,1429);
$z[10][4]['filename']="footer.htm";

?>