<li>

            <a href="[field:arcurl/]" title="[field:title/]" class="imga fl"><img src="[field:photo/]"/></a>
            <div class="info fl">
                <a href="[field:arcurl/]" title="[field:name/]" class="name fyahei">[field:dsnname/]</a>
                <p><span class="fb">担任职务：</span>[field:job/]</p>
                <p><span class="fb">工作经验：</span>[field:experience/]</p>                
				<p><span class="fb">收费标准：</span>[field:collectfees/]</p>               
                <a href="{dede:global.cfg_cmsurl/}plus/list.php?tid=24&designer=[field:dsnname/]" title="立即预约" target="_blank" class="team_btn order">立即预约</a>
            </div>
            <div class="work fl">
            	<p class="fb">代表作品</p>
                <pre class="pre">[field:production/]</pre>
            </div>

        </li>