<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:dsimg itemname="设计师图片" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsimg>

<field:dsnname itemname="设计师姓名" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsnname>

<field:dsnexp itemname="工作经验" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsnexp>

<field:dsnsfbz itemname="收费标准" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsnsfbz>

<field:dsnrqzs itemname="人气指数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsnrqzs>

<field:dsnsjln itemname="设计理念" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsnsjln>

<field:dnsyyrs itemname="预约人数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dnsyyrs>

<field:dsnnet itemname="设计师页面网址" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dsnnet>


<field:dfdfdf itemname="dsdf" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:dfdfdf>
