
<field:houses itemname="项目名称" autofield="1" type="select" isnull="true" default="请选择,拉菲庄园1,拉菲庄园2,拉菲庄园3"  maxlength="250" page="">
</field:houses>

<field:contact itemname="业主姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:sex itemname="业主性别" autofield="1" type="select" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>

<field:phone itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:content itemname="预约留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
