<?php
$z[0]=Array("global","",11,82);
$z[0][4]['name']="autoindex";
$z[0][4]['function']="@me%4==0?@me='end':@me='none'";
$z[1]=Array("arcurl","",98,113);
$z[2]=Array("title","",122,136);
$z[3]=Array("litpic","",177,192);
$z[4]=Array("title","",199,213);
$z[5]=Array("title","",281,295);
$z[6]=Array("title","",328,342);
$z[7]=Array("title","",468,482);
$z[8]=Array("pubdate","",579,626);
$z[8][4]['function']="MyDate('Y-m-d',@me)";

?>