<li>
		  <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="dis">
		  <em class="col_[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]">[field:autoindex runphp='yes']@me=$GLOBALS['autoindex'];[/field:autoindex]</em>
		  <div class="tt fyahei"><i>></i> [field:title/]</div>
		  <p class="fari">DATE:[field:pubdate function="MyDate('Y-m-d',@me)"/]              READ:[field:click/]</p>
		  </a>
		</li>