<?php
$z[0]=Array("arcurl","",28,43);
$z[1]=Array("title","",52,66);
$z[2]=Array("litpic","",91,106);
$z[3]=Array("title","",113,127);
$z[4]=Array("arcurl","",193,208);
$z[5]=Array("title","",217,231);
$z[6]=Array("title","",248,262);
$z[7]=Array("click","",304,318);
$z[8]=Array("designer","",371,388);
$z[9]=Array("arcurl","",493,508);
$z[10]=Array("title","",517,531);
$z[11]=Array("click","",597,611);
$z[12]=Array("pubdate","",643,690);
$z[12][4]['function']="MyDate('Y-m-d',@me)";

?>