<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",310,339);
$z[3][4]['name']="position";
$z[4]=Array("field","",339,358);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n      	  <li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n      	",551,788);
$z[5][4]['type']="son";
$z[5][4]['row']="7";
$z[5][4]['typeid']="11";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("type","[field:typelink/]",888,940);
$z[6][4]['typeid']="24";
$z[7]=Array("type","[field:typelink/]",1074,1126);
$z[7][4]['typeid']="62";
$z[8]=Array("field","",1330,1356);
$z[8][4]['name']="title";
$z[9]=Array("field","",1466,1487);
$z[9][4]['name']="content";
$z[10]=Array("include","",1532,1569);
$z[10][4]['filename']="footer.htm";

?>