
<field:contact itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:contact>

<field:addr itemname="地区" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:addr>

<field:cost itemname="预算" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:cost>

<field:area itemname="面积" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:area>

<field:dtime itemname="装修时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dtime>

<field:addrr itemname="装修要求" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:addrr>

<field:phone itemname="手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>
