<?php
$z[0]=Array("title","",22,36);
$z[1]=Array("process","",74,90);
$z[2]=Array("house","",113,127);
$z[3]=Array("style","",150,164);
$z[4]=Array("area","",187,200);
$z[5]=Array("cost","",223,236);
$z[6]=Array("maneger","",259,275);
$z[7]=Array("global","",307,333);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("title","",354,368);
$z[9]=Array("arcurl","",427,442);
$z[10]=Array("title","",451,465);

?>