<tr>
            <td>[field:title/]</td>
            <td class="orange">[field:process/]</td>
            <td>[field:house/]</td>
            <td>[field:style/]</td>
            <td>[field:area/]</td>
            <td>[field:cost/]</td>
            <td>[field:maneger/]</td>
            <td><a href="[field:global.cfg_cmsurl/]/a/book.html" title="[field:title/]" class="orange">报名</a></td>
            <td><a href="[field:arcurl/]" title="[field:title/]" class="view">详情</a></td>
        </tr>