<?php
$z[0]=Array("arcurl","",27,42);
$z[1]=Array("title","",51,65);
$z[2]=Array("litpic","",90,105);
$z[3]=Array("title","",112,126);
$z[4]=Array("arcurl","",192,207);
$z[5]=Array("title","",216,230);
$z[6]=Array("title","",247,261);
$z[7]=Array("click","",303,317);
$z[8]=Array("designer","",370,387);
$z[9]=Array("arcurl","",492,507);
$z[10]=Array("title","",516,530);
$z[11]=Array("click","",596,610);
$z[12]=Array("pubdate","",642,689);
$z[12][4]['function']="MyDate('Y-m-d',@me)";

?>