<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",519,551);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",607,639);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",758,785);
$z[6][4]['name']="cfg_basehost";
$z[7]=Array("global","",795,821);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",849,881);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",904,930);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("global","",981,1008);
$z[10][4]['name']="cfg_basehost";
$z[11]=Array("global","",1018,1044);
$z[11][4]['name']="cfg_webname";
$z[12]=Array("channel","\r\n		<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\"><em>[field:typename/]</em>[field:enname/]<i></i></a></li>\r\n		",1091,1381);
$z[12][4]['type']="top";
$z[12][4]['row']="6";
$z[12][4]['currentstyle']="<li class='current'><a href='~typelink~' title='~typename~'><em>~typename~</em><i>~enname~</i></a></li>";

?>