<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",321,348);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",387,417);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",467,499);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",555,587);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",706,733);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",743,769);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",797,829);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",852,878);
$z[8][4]['name']="cfg_webname";
$z[9]=Array("global","",945,972);
$z[9][4]['name']="cfg_basehost";
$z[10]=Array("global","",982,1008);
$z[10][4]['name']="cfg_webname";
$z[11]=Array("channel","\r\n		<li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\"><em>[field:typename/]</em><i>[field:enname/]</i></a></li>\r\n		",1055,1226);
$z[11][4]['type']="top";
$z[11][4]['row']="6";

?>