<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",126,158);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",217,243);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",312,341);
$z[3][4]['name']="position";
$z[4]=Array("field","",341,360);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n      	  <li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n      	",553,790);
$z[5][4]['type']="son";
$z[5][4]['row']="6";
$z[5][4]['typeid']="38";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("global","",890,915);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1068,1093);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("field","",1309,1335);
$z[8][4]['name']="title";
$z[9]=Array("field","",1445,1466);
$z[9][4]['name']="content";
$z[10]=Array("include","",1511,1548);
$z[10][4]['filename']="footer.htm";

?>