<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",126,158);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",217,243);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",307,336);
$z[3][4]['name']="position";
$z[4]=Array("field","",336,355);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n      	  <li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n      	",544,781);
$z[5][4]['type']="son";
$z[5][4]['row']="6";
$z[5][4]['typeid']="38";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("global","",881,906);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1051,1076);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("field","",1284,1310);
$z[8][4]['name']="title";
$z[9]=Array("field","",1420,1438);
$z[9][4]['name']="body";
$z[10]=Array("include","",1483,1520);
$z[10][4]['filename']="footer.htm";

?>