<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",310,339);
$z[3][4]['name']="position";
$z[4]=Array("field","",339,358);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n      	  <li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n      	",548,785);
$z[5][4]['type']="son";
$z[5][4]['row']="7";
$z[5][4]['typeid']="11";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("type","[field:typelink/]",885,937);
$z[6][4]['typeid']="24";
$z[7]=Array("type","[field:typelink/]",1071,1123);
$z[7][4]['typeid']="62";
$z[8]=Array("list","	\r\n        <li id=[field:global name=autoindex function=\"@me%3==0?@me='end':@me=''\"/]>\r\n            <a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"dis\">\r\n            <img src=\"[field:litpic/]\" alt=\"[field:title/]\" class=\"imga\" />\r\n            <p class=\"dis\">[field:title/]</p>\r\n            </a>\r\n        </li>\r\n			",1389,1787);
$z[8][4]['row']="6";
$z[8][4]['titlelen']="24";
$z[8][4]['orderby']="pubdate";
$z[8][4]['typeid']="14";
$z[9]=Array("pagelist","",1845,1924);
$z[9][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[9][4]['listsize']="15";
$z[10]=Array("include","",1971,2008);
$z[10][4]['filename']="footer.htm";

?>