<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",310,339);
$z[3][4]['name']="position";
$z[4]=Array("field","",339,358);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n	    ",546,692);
$z[5][4]['type']="son";
$z[5][4]['typeid']="2";
$z[5][4]['row']="4";
$z[6]=Array("arclist","\r\n			    <li>\r\n            <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\" class=\"imga\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /></a>\r\n            <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\" class=\"dis fl\"><i class=\"orange\">&nbsp;· </i>[field:title/]</a>\r\n        </li>\r\n			",808,1304);
$z[6][4]['row']="5";
$z[6][4]['titlelen']="40";
$z[6][4]['orderby']="pubdate";
$z[6][4]['typeid']="45";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[7]=Array("type","[field:typelink/]",1384,1436);
$z[7][4]['typeid']="24";
$z[8]=Array("type","[field:typelink/]",1570,1622);
$z[8][4]['typeid']="62";
$z[9]=Array("list","\r\n		      <li>\r\n        	<a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"imga fl\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /></a>\r\n            <div class=\"rArea fl\">\r\n            	<div class=\"time fari fl\">\r\n                	<a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"view\">+ VIEW</a>\r\n                    <i>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</i>\r\n                    <em>[field:pubdate function=\"MyDate('d',@me)\"/]</em>\r\n            	</div>\r\n                <h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"f14\">[field:title/]</a></h2>\r\n                <p> </p>\r\n            </div>\r\n        </li>\r\n		",1887,2628);
$z[9][4]['row']="6";
$z[9][4]['titlelen']="80";
$z[9][4]['orderby']="pubdate";
$z[9][4]['typeid']="27";
$z[9][4]['type']="image.";
$z[10]=Array("pagelist","",2686,2765);
$z[10][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[10][4]['listsize']="20";
$z[11]=Array("include","",2812,2849);
$z[11][4]['filename']="footer.htm";

?>