<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",126,158);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",217,243);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",311,340);
$z[3][4]['name']="position";
$z[4]=Array("field","",340,359);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n      	  <li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n      	",552,789);
$z[5][4]['type']="son";
$z[5][4]['row']="7";
$z[5][4]['typeid']="11";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("field","",1363,1381);
$z[6][4]['name']="body";
$z[7]=Array("include","",2987,3024);
$z[7][4]['filename']="footer.htm";

?>