<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",310,339);
$z[3][4]['name']="position";
$z[4]=Array("field","",339,358);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n      	  <li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n      	",548,785);
$z[5][4]['type']="son";
$z[5][4]['row']="7";
$z[5][4]['typeid']="11";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("type","[field:typelink/]",885,937);
$z[6][4]['typeid']="24";
$z[7]=Array("type","[field:typelink/]",1071,1123);
$z[7][4]['typeid']="62";
$z[8]=Array("list","\r\n		      <tr>\r\n            <td>[field:title/]</td>\r\n            <td class=\"orange\">[field:process/]</td>\r\n            <td>[field:house/]</td>\r\n            <td>[field:style/]</td>\r\n            <td>[field:area/]</td>\r\n            <td>[field:cost/]</td>\r\n            <td>[field:maneger/]</td>\r\n            <td><a href=\"[field:global.cfg_basehost/]/a/book.html\" title=\"[field:title/]\" class=\"orange\">报名</a></td>\r\n            <td><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"view\">详情</a></td>\r\n        </tr>\r\n			",1746,2350);
$z[8][4]['row']="15";
$z[8][4]['titlelen']="24";
$z[8][4]['orderby']="pubdate";
$z[8][4]['typeid']="18";
$z[9]=Array("pagelist","",2411,2490);
$z[9][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[9][4]['listsize']="15";
$z[10]=Array("include","",2537,2574);
$z[10][4]['filename']="footer.htm";

?>