<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",310,339);
$z[3][4]['name']="position";
$z[4]=Array("field","",339,358);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n	    ",548,695);
$z[5][4]['type']="son";
$z[5][4]['typeid']="19";
$z[5][4]['row']="7";
$z[6]=Array("type","[field:typelink/]",795,847);
$z[6][4]['typeid']="24";
$z[7]=Array("type","[field:typelink/]",981,1033);
$z[7][4]['typeid']="62";
$z[8]=Array("list","\r\n                <li>\r\n            <dt><em>Q</em><p class=\"orange\"><a href=\"[field:arcurl/]\" style=\"color:#f60;\" target=\"_blank\">[field:title/]</a></p></dt>\r\n            <dd><em class=\"col\">A</em><pre class=\"def ove\">[field:description /]</pre></dd>\r\n        </li>\r\n        ",1302,1652);
$z[8][4]['row']="5";
$z[8][4]['titlelen']="80";
$z[8][4]['orderby']="pubdate";
$z[8][4]['typeid']="23";
$z[9]=Array("include","",1713,1750);
$z[9][4]['filename']="footer.htm";

?>