<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",310,339);
$z[3][4]['name']="position";
$z[4]=Array("field","",339,358);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n      	  <li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n      	",550,787);
$z[5][4]['type']="son";
$z[5][4]['row']="7";
$z[5][4]['typeid']="11";
$z[5][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("global","",887,912);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1065,1090);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("arclist","\r\n		   <li id=[field:global name=autoindex function=\"@me%3==0?@me='end':@me=''\"/]>\r\n            <img src=\"[field:litpic/]\" alt=\"[field:title/]\" class=\"imga\" />\r\n			<p class=\"dis\">[field:title/]</p>\r\n        </li>\r\n		",1378,1676);
$z[8][4]['row']="15";
$z[8][4]['titlelen']="24";
$z[8][4]['orderby']="pubdate";
$z[8][4]['typeid']="17";
$z[9]=Array("include","",1736,1773);
$z[9][4]['filename']="footer.htm";

?>