<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",311,340);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n	    ",534,681);
$z[4][4]['type']="son";
$z[4][4]['typeid']="19";
$z[4][4]['row']="7";
$z[5]=Array("global","",783,808);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",961,986);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("field","",1202,1228);
$z[7][4]['name']="title";
$z[8]=Array("field","",1323,1344);
$z[8][4]['name']="content";
$z[9]=Array("include","",1387,1424);
$z[9][4]['filename']="footer.htm";

?>