<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",126,158);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",217,243);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",312,341);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n	    ",535,682);
$z[4][4]['type']="son";
$z[4][4]['typeid']="19";
$z[4][4]['row']="7";
$z[5]=Array("global","",784,809);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",962,987);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("field","",1203,1229);
$z[7][4]['name']="title";
$z[8]=Array("field","",1324,1345);
$z[8][4]['name']="content";
$z[9]=Array("include","",1388,1425);
$z[9][4]['filename']="footer.htm";

?>