<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",311,340);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n	    ",534,681);
$z[4][4]['type']="son";
$z[4][4]['typeid']="19";
$z[4][4]['row']="7";
$z[5]=Array("type","[field:typelink/]",783,835);
$z[5][4]['typeid']="24";
$z[6]=Array("type","[field:typelink/]",969,1021);
$z[6][4]['typeid']="62";
$z[7]=Array("field","",1225,1251);
$z[7][4]['name']="title";
$z[8]=Array("field","",1346,1367);
$z[8][4]['name']="content";
$z[9]=Array("include","",1410,1447);
$z[9][4]['filename']="footer.htm";

?>