<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head2.htm";
$z[1]=Array("global","",126,158);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",217,243);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",312,341);
$z[3][4]['name']="position";
$z[4]=Array("field","",341,360);
$z[4][4]['name']="title";
$z[5]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n	    ",554,701);
$z[5][4]['type']="son";
$z[5][4]['typeid']="19";
$z[5][4]['row']="7";
$z[6]=Array("field","",1155,1181);
$z[6][4]['name']="title";
$z[7]=Array("field","",1276,1294);
$z[7][4]['name']="body";
$z[8]=Array("include","",1337,1374);
$z[8][4]['filename']="footer.htm";

?>