<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",125,157);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",216,242);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",310,339);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\"  target=\"_blank\">[field:typename/]</a></li>\r\n	    ",529,676);
$z[4][4]['type']="son";
$z[4][4]['typeid']="19";
$z[4][4]['row']="7";
$z[5]=Array("global","",776,801);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",954,979);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("arclist","\r\n				<option value=\"[field:dsnname/]\">[field:dsnname/]</option>\r\n				",6042,6202);
$z[7][4]['titlelen']="24";
$z[7][4]['typeid']="10";
$z[7][4]['addfields']="dsnname";
$z[7][4]['channelid']="18";
$z[8]=Array("include","",9295,9332);
$z[8][4]['filename']="footer.htm";

?>